runtime: php55
api_version: 1

handlers:
 - url: /quick
   script: getQuickEmpty.php

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/roomfinder-187219:us-central1:uoitroomfinder;dbname=roomFinder
  MYSQL_USER: ds
  MYSQL_PASSWORD: ds