runtime: php55
api_version: 1
handlers:
 - url: /quick
   script: getQuickEmpty.php
 - url: /byname
   script: getByName.php
 - url: /schedule
   script: getRoomSchedule.php
 - url: /enterreview
   script: enterReview.php
 - url: /getreviews
   script: getReviews.php
 - url: /updaterating
   script: updateRatings.php
env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/roomfinder-187219:us-central1:uoitroomfinder;dbname=roomFinder
  MYSQL_USER: ds
  MYSQL_PASSWORD: ds